fullnameOverride: ""

env:
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        name: hf-secret
        key: HF_TOKEN
        optional: false

args:
  - --model_id=meta-llama/Llama-3.1-8B-Instruct
  - --model_name=llama-3-1-8b-instruct
  - --max_model_len=8192
  - --enable-auto-tool-choice
  - --tool-call-parser=llama3_json

annotations: {}

labels: {}

resources:
  limits:
    cpu: "12"
    memory: 24Gi
    nvidia.com/gpu: "1"
  requests:
    cpu: "8"
    memory: 12Gi
    nvidia.com/gpu: "1"

metrics:
  enabled: false
  endpoints: []
    # - port: http-usermetric
    #   path: /metrics